apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  labels:
    app: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: simple-app
          image: 'biraluu/simple-app:'
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          envFrom:
            - configMapRef:
                name: simple-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  labels:
    app: simple-app
spec:
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
  template:
    spec:
      containers:
        - image: biraluu/simple-app:{{IMAGE_TAG}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-app-config
  labels:
    app: simple-app
data:
  APP_ENV: "development"
